src/PMS/PMS/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

from borrow.ser_views import BorrowByViewSet
from bugs.ser_views import BugByPViewSet
from problems.ser_views import ProblemByPViewSet, ProblemByRViewSet, ProblemByBViewSet
from bases.views import index
from django.conf.urls.static import static
from django.conf import settings

from requests.ser_views import SubRequestViewSet, RequestByPViewSet

router = DefaultRouter()
router.register(r'requests/(?P<request_id>\d+)/requests', SubRequestViewSet)
router.register(r'requests/(?P<request_id>\w+)/problems', ProblemByRViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/requests', RequestByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/problems', ProblemByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/bugs', BugByPViewSet)
router.register(r'bugs/(?P<bug_id>\d+)/problems', ProblemByBViewSet)
router.register(r'borrow', BorrowByViewSet)

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^stock/', include('stock.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^borrow/', include('borrow.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^requests/', include('requests.urls')),
    url(r'^problems/', include('problems.urls')),
    url(r'^home', include('bases.urls')),
    url(r'^bugs/', include('bugs.urls')),
    url(r'^tests/', include('tests.urls')),
    url(r'^helpdesk/', include('helpdesk.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
    url(r'^users/', include('users.urls')),
)

src/PMS/requests/urls.py
from django.urls import re_path as url

from projects.ajax_views import *
from requests.views import *

urlpatterns = [
    url(r'^page/(?P<pk>\d+)/$', request_page, name="request_page"),
    url(r'^edit/(?P<pk>\d+)/$', request_edit, name="request_edit"),
    url(r'^add/$', request_create, name="request_create"),
    url(r'^list/$', request_list, name="request_list"),
    url(r'^detail/(?P<pk>\d+)/$', request_detail, name="request_detail"),
    url(r'^delete/(?P<pk>\d+)/$', request_delete, name="request_delete"),
    url(r'^$', get_request, name="get_request"),
    url(r'^index/(?P<pk>\d+)/$', request_index, name="request_index"),
    url(r'^receive', request_receive, name="request_receive"),
    url(r'change_status', change_status, name="change_status"),
    url(r'^rfd/(?P<pk>\d+)', request_file_delete, name="request_file_delete"),
    url(r'^history', request_history, name="request_history"),
    url(r'^(?P<no>\w+)$', request_guest, name="request_guest"),
    url(r'^reply/(?P<pk>\d+)/$', request_reply, name="request_reply"),
    url(r'^reply_delete/(?P<pk>\d+)/$', reply_delete, name="request_reply_delete"),
    url(r'^reply_edit/(?P<pk>\d+)/$', reply_edit, name="reply_edit"),
]

src/PMS/requests/models.py
import os

from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.dispatch import receiver

# desc = RichTextUploadingField(null=True, blank=True, external_plugin_resources=[(
#         'youtube',
#         '/static/ckeditor/ckeditor/plugins/youtube',
#         'plugin.js', )],)


class Request(models.Model):
    request_no = models.CharField(
        'Request No.', max_length=20, unique=True)  # 需求單號
    title = models.CharField(max_length=100)  # 標題
    desc = RichTextUploadingField(null=True, blank=True, external_plugin_resources=[(
        'youtube',
        '/static/ckeditor/ckeditor/plugins/youtube',
        'plugin.js', )],)
    level = models.ForeignKey(
        'requests.Level', related_name='request_level', on_delete=models.DO_NOTHING)  # 緊急程度
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='request_owner',
                              on_delete=models.DO_NOTHING, null=True, blank=True)  # 需求負責人
    start_date = models.DateField(null=True, blank=True)  # 需求開始日期
    due_date = models.DateField(null=True, blank=True)  # 完工日期
    actual_date = models.DateField(null=True, blank=True)  # 實際完成日期
    status = models.ForeignKey(
        'bases.Status', related_name='request_level', on_delete=models.DO_NOTHING)  # 狀態
    is_test = models.BooleanField(default=False)  # 是否需要進行測試
    test_data = models.BooleanField(default=False)  # 是否有測試資料
    process_rate = models.IntegerField(
        default=0, null=True, blank=True)  # 完成度 系統運算
    belong_to = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True)  # 上層
    file_list = models.CharField(max_length=200, blank=True)  # 要卡控檔案上限
    project = models.ForeignKey(
        'projects.Project', related_name='request_project', on_delete=models.CASCADE)  # 歸屬專案
    estimate_time = models.IntegerField(
        default=0, null=True, blank=True)  # 預估時間(hr)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='request_create_at')  # 建立者
    update_at = models.DateTimeField(auto_now=True, null=True)  # 修改日期
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='request_update_at')  # 修改者

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('request_detail', kwargs={'pk': self.pk})


class Level(models.Model):
    level_en = models.CharField(max_length=50)
    level_cn = models.CharField(max_length=50)
    level_desc = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True, editable=True)
    create_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='level_create_at')
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='level_update_at')

    def __str__(self):
        return self.level_cn


class Request_attachment(models.Model):
    request = models.ForeignKey(
        'Request', related_name='request_files', on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/requests/%Y/%m/')
    description = models.CharField(max_length=50, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, editable=True)


@receiver(models.signals.post_delete, sender=Request_attachment)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.files:
        if os.path.isfile(instance.files.path):
            os.remove(instance.files.path)

class Request_reply(models.Model):
    request = models.ForeignKey(
        'Request', related_name='request_reply', on_delete=models.CASCADE)
    desc = RichTextUploadingField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='request_reply_create_at')  # 建立者

    def get_absolute_url(self):
        return reverse('request_detail', kwargs={'pk': self.pk})

src/PMS/requests/forms.py
from bootstrap_datepicker_plus.widgets import DatePickerInput
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from django import forms
from django.utils.translation import gettext_lazy as _
from bases.models import Status
from requests.models import Request, Level, Request_reply
from datetime import datetime, timedelta
from users.models import CustomUser

class RequestHistoryForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = ('status', 'start_date', 'due_date',)

    status = forms.ModelChoiceField(required=False, label=_(
        'status'), queryset=Status.objects.all(), initial=1)
    start_date = forms.DateField(label="建立日期(起)")
    due_date = forms.DateField(label="建立日期(迄)")

    def __init__(self, *args, submit_title='Submit', **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True

        self.helper.layout = Layout(
            Div(Div('start_date', css_class='col-md-3'),
                Div('due_date', css_class='col-md-3'),
                Div('status', css_class='col-md-3'),
                Div(Submit('submit', '查詢', css_class='btn btn-info'), css_class='col-md-3 d-flex align-items-center'),
                css_class='row'),
        )

        self.fields['start_date'].widget = DatePickerInput(
            attrs={'value': (datetime.now()-timedelta(days=45)).strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

        self.fields['due_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

class RequestReceiveForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = (
            'start_date', 'due_date', 'estimate_time'
        )
        estimate_time = forms.IntegerField(required=False, label=_('estimate_time'), widget=forms.NumberInput(),
                                           initial=0, )
        start_date = forms.DateField(label=_('starttime'))
        due_date = forms.DateField(label=_('finishtime'))

    def __init__(self, *args, submit_title='Submit', **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True

        self.helper.layout = Layout(
            Div(Div('start_date', css_class='col-md-6'),
                Div('due_date', css_class='col-md-6'),
                css_class='row'),
            Div('estimate_time'),
        )

        self.fields['start_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        ).start_of('request days')

        self.fields['due_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        ).end_of('request days')

    # def clean_due_date(self):
    #     if self.cleaned_data['start_date'] <= self.cleaned_data['due_date']:
    #         return self.cleaned_data['due_date']
    #     else:
    #         raise forms.ValidationError(u"預計完成日期不能小於開始日期")

class RequestReplyForm(forms.ModelForm):
    class Meta:
        model = Request_reply
        fields = ('desc',)

        desc = forms.CharField(required=False, widget=CKEditorUploadingWidget())

    def __init__(self, *args, submit_title='Submit', **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True
        self.fields['desc'].label = ""
        self.helper.layout = Layout(
            Div(
                Div('desc', css_class='col-12'),
                css_class='row'
            )
        )

class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = (
            'title', 'start_date', 'due_date', 'process_rate', 'estimate_time', 'level', 'owner', 'desc',
            'status', 'actual_date',)

    level = forms.ModelChoiceField(required=True, label=_('level'), queryset=Level.objects.all(), initial=2)
    title = forms.CharField(required=True, label=_('title'))
    desc = forms.CharField(required=False, label=_('desc'), widget=CKEditorUploadingWidget())
    status = forms.ModelChoiceField(required=True, label=_('status'), queryset=Status.objects.all(), initial=1)
    owner = forms.ModelChoiceField(required=False, label=_('owner'), queryset=CustomUser.objects.all())
    estimate_time = forms.IntegerField(required=False, label=_('estimate_time'), widget=forms.NumberInput(), initial=0, )
    start_date = forms.DateField(label=_('starttime'))
    due_date = forms.DateField(label=_('finishtime'))
    actual_date = forms.DateField(required=False, label=_('actualtime'))

    def __init__(self, *args, submit_title='Submit', **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True

        self.helper.layout = Layout(
            Div(
                Div('level', css_class='col-md-6'),
                Div('status', css_class='col-md-6'),
                css_class='row'),
            Div('title'),
            Div('desc'),
            Div('actual_date'),
            Div(Div('start_date', css_class='col-md-6'),
                Div('due_date', css_class='col-md-6'),
                css_class='row'),
            Div(Div('owner', css_class='col-md-6'),
                Div('estimate_time', css_class='col-md-6'),
                css_class='row'),
        )

        self.fields['start_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

        self.fields['due_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

        self.fields['actual_date'].widget = DatePickerInput(
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

src/PMS/requests/templates/requests/reply_edit.html
{% extends 'bases/menu_base.html' %}

{% load crispy_forms_tags %}

{% load static %}
{% load i18n %}
{% block breadcrumb %}

{% endblock %}
{% block content %}
{% if user.is_authenticated %}
        <form action="/requests/reply_edit/{{ reply.pk }}/" method="post" class="form-group font-weight-bold align-middle" id="request_form" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header pb-1 pt-1">
                <div class="row">
                    <div class="col-sm-11 align-self-center">
                        COMMENT
                    </div>
                    <div class="ml-md-auto">
                        <button type="submit" class="btn btn-warning btn-sm" id="send">{% trans "Save" %}</button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {% csrf_token %}
                    {% crispy form %}
                </div>
            </div>
        </div>
        </form>
        {% endif %}
{% endblock %}

{% block js %}

{% endblock js %}

{% block css %}
<style>
.django-ckeditor-widget {
    width: 100%;
}
</style>
{% endblock %}

src/PMS/requests/templates/requests/request_detail.html
{% extends 'bases/menu_base.html' %}

{% load static %}
{% load i18n %}
{% block title %}
PMS Task Detail 詳細資料
{% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url "request_page" pk=data.project.pk %}">{{ data.project.name }}</a></li>
    {% for dad in bread %}
        <li class="breadcrumb-item"><a href="{% url "request_detail" pk=dad.pk %}">{{ dad.title }}</a></li>
    {% endfor %}
    <li class="breadcrumb-item active" aria-current="page">{{ data.title }}</li>
{% endblock %}
{% block content %}
{% include 'requests/request_base.html' %}
{% endblock %}

src/PMS/requests/templates/requests/request_edit.html
{% extends 'bases/menu_base.html' %}

{% load crispy_forms_tags %}

{% load static %}
{% load i18n %}
{% block title %}建立需求{% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'request_page' pk=project.pk %}">{{ project.name }}</a></li>
    {% if form.instance.id %}
    <li class="breadcrumb-item"><a href="{% url 'request_detail' pk=require.pk %}">{{ require.title }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% trans "request_edit" %}</li>
    {% else %}
    <li class="breadcrumb-item active" aria-current="page">{% trans "request_create" %}</li>
    {% endif %}
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
      <div class="card">
          <div class="card-header">
          {% if form.instance.id %}
            {% trans "request_edit" %}
          {% else %}
            {% trans "request_create" %}
          {% endif %}
          </div>
          {% include "bases/attach_form.html" %}
      </div>
  </div>
  <div class="col-md-1"></div>
</div>

{% endblock %}

{% block js %}
<script src="/static/ckeditor/ckeditor-init.js" type="text/javascript"></script>
<script src="/static/ckeditor/ckeditor/ckeditor.js" type="text/javascript"></script>
<script>
$(function() {
    FinishCheck();

    $("#id_status").change(function(){
        FinishCheck();
    });
});


//狀態為Finished才出現實際完成時間
function FinishCheck() {
    if($("#id_status :selected").text().toUpperCase()=="DONE")
    {
        $("#div_id_actual_date").show();
    }
    else
    {
        $("#id_actual_date").val('');
        $("#div_id_actual_date").hide();
    }
}
</script>
{% endblock js %}

{% block css %}
<style>
.django-ckeditor-widget {
width: 100%;
}
</style>
{% endblock %}

src/PMS/requests/templates/requests/request_guest.html
{% load static %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'jquery-ui\jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-4.1.3\css\bootstrap.min.css' %}">
    <script src="{% static 'jquery\jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'jquery-ui\jquery-ui.min.js' %}"></script>
    <script src="{% static 'bootstrap-4.1.3\js\bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fontawesome-5.4.2\css\all.css' %}">
</head>
<body>
<div class="p-3">
{% include 'requests/request_base.html' %}
</div>
</body>
<style>
    th{
        font-size: 16px;font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
    }
    td{
        font-size: 15px;font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
    }
    option{
        font-size: 15px;font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
    }
    a{
        font-size: 17px;font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
    }
    div{
        font-family:arial,sans-serif,Meiryo,Microsoft JhengHei;
    }
    html, body {
      height: 100%;
    }
</style>
</html>

src/PMS/requests/templates/requests/request_history.html
{% extends 'bases/menu_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block title %} {% trans "project_manage" %} {% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'request_page' pk=project.pk %}">{{ project.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">需求紀錄</li>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header pb-1 pt-1">
        <div class="row">
            查詢條件
        </div>
    </div>
    <div class="card-body">
        <form action="" method="post" class="form-group font-weight-bold align-middle" id="request_form" enctype="multipart/form-data">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
</div>
<table class="table table-bordered table-striped" style="font-size:0.9em;">
    <thead class="thead-dark">
        <tr>
            <th>需求編號</th>
            <th>標題</th>
            <th>緊急狀態</th>
            <th>擁有者</th>
            <th>預計起始時間</th>
            <th>預計完成時間</th>
            <th>實際完成時間</th>
            <th>狀態</th>
            <th>建立者</th>
            <th>建立日期</th>
            <th>更新者</th>
            <th>更新日期</th>
        </tr>
    </thead>
    <tbody>
        {% for require in requires %}
            <tr>
                <td><a href="/requests/detail/{{ require.pk }}/">{{ require.request_no }}</a></td>
                <td>{{ require.title }}</td>
                <td>{{ require.level }}</td>
                <td>{{ require.owner|default:"" }}</td>
                <td>{{ require.start_date|date:'Y-m-d' }}</td>
                <td>{{ require.due_date|date:'Y-m-d' }}</td>
                <td>{{ require.actual_date|default:""|date:'Y-m-d' }}</td>
                <td>{{ require.status }}</td>
                <td>{{ require.create_by }}</td>
                <td>{{ require.create_at|date:'Y-m-d' }}</td>
                <td>{{ require.update_by }}</td>
                <td>{{ require.update_at|date:'Y-m-d' }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

{% block js %}
<script src="{% static 'bootstrap-table-develop\src\bootstrap-table.js' %}"></script>
<link rel="stylesheet"  type="text/css" href="{% static 'bootstrap-table-develop\src\bootstrap-table.css' %}">
<script src="{% static 'bootstrap-table-develop\src\extensions\filter-control\bootstrap-table-filter-control.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-table-develop\src\extensions\filter-control\bootstrap-table-filter-control.css' %}">
<script src="{% static 'bootstrap_table/table.js' %}"></script>
<script>

</script>
{% endblock %}

src/PMS/requests/templates/requests/request_list.html
{% extends 'bases/menu_base.html' %}

{% load crispy_forms_tags %}

{% load static %}
{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">RequestList</li>
{% endblock %}
{% block content %}
<table class="table table-sm table-bordered table-light table-striped table-hover mb-3">
    <thead>
    <tr class="text-md-center align-middle">
        <th width="10%">#需求編號</th>
        <th width="10%">標題</th>
        <th width="10%">優先等級</th>
        <th width="10%">狀態</th>
        <th width="10%">負責人</th>
        <th width="10%">預計開始時間</th>
        <th width="10%">預計完成時間</th>
        <th width="10%">完成度</th>
        <th width="10%">子需求</th>
        <th width="10%">問題</th>
        <th width="60"></th>
    </tr>
    </thead>
    <tbody>
    {% for request in requests %}
        <tr class="text-md-center align-middle">
            <td><a href="{% url 'request_detail' request.pk %}">{{ request.request_no }}</a></td>
            <td>{{ request.title }}</td>
            <td>{{ request.level }}</td>
            <td>{{ request.status }}</td>
            <td>{{ request.owner }}</td>
            <td>{{ request.start_date|date:"Y-m-d" }}</td>
            <td class="text-md-left">{{ request.due_date|date:"Y-m-d" }}</td>
            <td class="text-md-left">{{ request.process_rate }}</td>
            <td class="text-md-left">{{ request.sub_num }}</td>
            <td class="text-md-left">{{ request.problem_num }}</td>
            <td>
                <a href="#" class="text-secondary btn-edit" data-key="{{ request.pk }}" data-toggle="modal"
                   data-target="#modal-change"><i class="fas fa-pen-square"></i></a>&nbsp;
                <a href="#" class="text-secondary btn-del" data-key="{{ request.pk }}"><i
                        class="fas fa-minus-square"></i></a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block js %}
    {{ block.super }}
{% endblock js %}

src/PMS/requests/templates/requests/request_receive.html
{% extends 'bases/menu_base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% trans "Receive Request" %}</title>
{% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url "project_manage" data.project.pk %}">{{ data.project.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url "request_detail" data.pk %}">{{ data.title }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{% trans "Receive Request" %}</li>
{% endblock %}
{% block content %}
<form action="" method="post" class="form-group font-weight-bold align-middle" id="request_form" enctype="multipart/form-data">
  <div class="card">
    <div class="card-header">{% trans "Receive Request" %}</div>
    <div class="card-body">
    {% csrf_token %}
    {% crispy form %}
  </div>
    <div class="card-footer text-center">
    <button type="submit" class="btn btn-primary" id="send">{% trans "save" %}</button>
    <input type=button class="btn btn-primary" value="Cancel" onClick="javascript:history.go(-1);">
  </div>
  </div>
</form>
{% endblock %}