src/PMS/PMS/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

from borrow.ser_views import BorrowByViewSet
from bugs.ser_views import BugByPViewSet
from problems.ser_views import ProblemByPViewSet, ProblemByRViewSet, ProblemByBViewSet
from bases.views import index
from django.conf.urls.static import static
from django.conf import settings

from requests.ser_views import SubRequestViewSet, RequestByPViewSet

router = DefaultRouter()
router.register(r'requests/(?P<request_id>\d+)/requests', SubRequestViewSet)
router.register(r'requests/(?P<request_id>\w+)/problems', ProblemByRViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/requests', RequestByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/problems', ProblemByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/bugs', BugByPViewSet)
router.register(r'bugs/(?P<bug_id>\d+)/problems', ProblemByBViewSet)
router.register(r'borrow', BorrowByViewSet)

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^stock/', include('stock.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^borrow/', include('borrow.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^requests/', include('requests.urls')),
    url(r'^problems/', include('problems.urls')),
    url(r'^home', include('bases.urls')),
    url(r'^bugs/', include('bugs.urls')),
    url(r'^tests/', include('tests.urls')),
    url(r'^helpdesk/', include('helpdesk.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
    url(r'^users/', include('users.urls')),
)

src/PMS/stock/urls.py
from django.urls import re_path as url
from stock.views import search, location_setting, storage_edit, location_list, location_add, location_edit, \
    location_save, bin_add, bin_edit, bin_save, bin_list, stock_in, stock_out, item_search_popup, TypeAPI, ItemAPI, \
    stockin_detail, get_item_info, bin_search_popup, LocationAPI, get_bin_info, stockout_detail, StockItemAPI, \
    item_stock_search_popup, recent_history, stock_history, stock_search, stock_search_action, stock_search_excel, \
    StorageBinAPI, LocationBinAPI, stockin_search, stockout_search

urlpatterns = [
    url(r'^search/', search, name='stock_search'),
    url(r'^item_search_popup/', item_search_popup, name='item_search_popup'),
    url(r'^item_stock_search_popup/', item_stock_search_popup, name='item_stock_search_popup'),
    url(r'^bin_search_popup/', bin_search_popup, name='bin_search_popup'),
    url(r'^location_setting/', location_setting, name='location_setting'),
    url(r'^location/', location_list, name='location_list'),
    url(r'^location_add/', location_add, name='location_add'),
    url(r'^location_edit/', location_edit, name='location_edit'),
    url(r'^location_save/', location_save, name='location_save'),
    url(r'^location_api/(?P<storage_code>\w+)', LocationAPI, name='stock_location_api'),
    url(r'^storage_edit/', storage_edit, name='storage_edit'),
    url(r'^storage_bin_api/', StorageBinAPI, name='storage_bin_api'),
    url(r'^location_bin_api/(?P<location_code>\w+)', LocationBinAPI, name='location_bin_api'),
    url(r'^bin/(?P<storage_code>\w+)/(?P<location_code>[\w-]+)', bin_list, name='bin_list'),
    url(r'^bin_add/', bin_add, name='bin_add'),
    url(r'^bin_edit/', bin_edit, name='bin_edit'),
    url(r'^bin_save/', bin_save, name='bin_save'),
    url(r'^stock_in/', stock_in, name='stock_in'),
    url(r'^stockin_detail/(?P<pk>\w+)/$', stockin_detail, name='stockin_detail'),
    url(r'^stock_out/', stock_out, name='stock_out'),
    url(r'^stockout_detail/(?P<pk>\w+)/$', stockout_detail, name='stockout_detail'),
    url(r'^typeapi/(?P<category_id>\d+)', TypeAPI, name='stock_typeapi'),
    url(r'^itemapi/', ItemAPI, name='stock_catogory_itemapi'),
    url(r'^stockitemapi/', StockItemAPI, name='stock_catogory_stockitemapi'),
    url(r'^getitemapi/', get_item_info, name='stock_get_item_info'),
    url(r'^getbinapi/', get_bin_info, name='stock_get_bin_info'),
    url(r'^recent_history/', recent_history, name='recent_history'),
    url(r'^stock_history/', stock_history, name='stock_history'),
    url(r'^stock_search/', stock_search, name='stock_search'),
    url(r'^stock_search_excel/', stock_search_excel, name='stock_search_excel'),
    url(r'^stock_search_action/', stock_search_action, name='stock_search_action'),
    url(r'^stockin_search/', stockin_search, name='stockin_search'),
    url(r'^stockout_search/', stockout_search, name='stockout_search'),
]

src/PMS/stock/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from inventory.models import Item


class MovementType(models.Model):
    mvt_code = models.CharField(max_length=5, primary_key=True)
    mvt_name = models.CharField(max_length=20, blank=False, null=False)
    desc = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='mvt_create_by')  # 建立者

    def __str__(self):
        return self.desc


class Storage(models.Model):
    storage_code = models.CharField(max_length=6, primary_key=True)
    desc = models.CharField(max_length=200, blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='storage_update_by')
    enable = models.BooleanField(default=True)

    def __str__(self):
        return self.desc


class Location(models.Model):
    storage = models.ForeignKey(Storage, related_name='storage_location', on_delete=models.DO_NOTHING)
    location_code = models.CharField(max_length=10, primary_key=True)
    location_name = models.CharField(max_length=20, blank=False, null=False)
    desc = models.CharField(max_length=200, blank=True, null=True)
    enable = models.BooleanField(default=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='location_update_by')

    def __str__(self):
        return self.desc


class Bin(models.Model):
    location = models.ForeignKey(Location, related_name='location_bin', on_delete=models.DO_NOTHING)
    bin_code = models.CharField(max_length=20, primary_key=True)
    bin_name = models.CharField(max_length=200, blank=True, null=True)
    enable = models.BooleanField(default=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='bin_update_by')

    def __str__(self):
        return self.bin_name


class Stock(models.Model):
    item = models.ForeignKey(Item, related_name='stock_item', on_delete=models.DO_NOTHING)
    bin = models.ForeignKey(Bin, related_name='stock_bin', on_delete=models.DO_NOTHING)
    qty = models.IntegerField(default=0)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='stock_update_by')


class StockHistory(models.Model):
    batch_no = models.CharField(max_length=20, blank=False, null=False)
    mtr_doc = models.CharField(max_length=10, blank=True, null=True)
    item = models.ForeignKey(Item, related_name='stock_hist_item', on_delete=models.DO_NOTHING)
    bin = models.ForeignKey(Bin, related_name='stock_hist_bin', on_delete=models.DO_NOTHING)
    mvt = models.ForeignKey(MovementType, related_name='stock_hist_mvt', on_delete=models.DO_NOTHING)
    plus_qty = models.IntegerField(default=0)
    minus_qty = models.IntegerField(default=0)
    remain_qty = models.IntegerField(default=0)
    desc = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now=True, null=True)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='stock_hist_update_by')


class StockInForm(models.Model):
    form_no = models.CharField(max_length=20, primary_key=True)
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='stockin_form_requester')
    apply_date = models.CharField(max_length=10, blank=False, null=False)
    pr_no = models.CharField(max_length=100, blank=True, null=True)
    reason = models.CharField(max_length=2000, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='stockin_form_create_by')  # 建立者

    def get_absolute_url(self):
        return reverse('stockin_detail', kwargs={'pk': self.pk})


class StockOutForm(models.Model):
    form_no = models.CharField(max_length=20, primary_key=True)
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='stockout_form_requester')
    apply_date = models.CharField(max_length=10, blank=False, null=False)
    reason = models.CharField(max_length=2000, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='stockout_form_create_by')  # 建立者

    def get_absolute_url(self):
        return reverse('stockout_detail', kwargs={'pk': self.pk})

src/PMS/stock/templates/stock/bin_edit.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block js %}
<script>
function cancel() {
    $("#cancel_form").submit();
}

$(document).ready(function() {
    $("#save_form").submit(function(e) {
        $("#id_location").prop('disabled', false);
    });
});
</script>
{% endblock js %}
{% block content %}
<form id="cancel_form" action="{% url 'bin_list' storage_code location_code %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{ location.location_code }}" name="pk" />
</form>
<div class="pt-3">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <form id="save_form" action="{% url 'bin_save' %}" method="post">
                {% csrf_token %}
                {% crispy form %}
                <div style="text-align: center" class="p-3">
                    <input type="submit" value="儲存" class='btn btn-info' onclick="submit();" />
                    <input type="hidden" value="{{ action }}" name="action" />
                    <input type="hidden" value="{{ location_code }}" name="location_code" />
                    <input type="button" class="btn btn-info" value="取消" onClick="cancel();">
                </div>
            </form>
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endblock %}
{% block menu %}
<a href="{% url 'bin_list' storage_code location_code %}" class='btn btn-info'><i class="fas fa-arrow-left fa-1x"></i></a>
{% endblock %}

src/PMS/stock/templates/stock/location_edit.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block js %}
<script>
function cancel() {
    $("#cancel_form").submit();
}

$(document).ready(function() {
    $("#save_form").submit(function(e) {
        $("#id_plant").prop('disabled', false);
        $("#id_storage").prop('disabled', false);
    });
});
</script>
{% endblock js %}
{% block content %}
<form id="cancel_form" action="{% url 'location_list' %}" method="post">
    {% csrf_token %}
    <input type="hidden" value="{{ location.storage.storage_code }}" name="pk" />
</form>
<div class="pt-3">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <form id="save_form" action="{% url 'location_save' %}" method="post">
                {% csrf_token %}
                {% crispy form %}
                <div style="text-align: center" class="p-3">
                    <input type="submit" value="儲存" class='btn btn-info' onclick="submit();" />
                    <input type="hidden" value="{{ action }}" name="action" />
                    <input type="hidden" value="{{ storage_code }}" name="storage_code" />
                    <input type="button" class="btn btn-info" value="取消" onClick="cancel();">
                </div>
            </form>
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endblock %}

src/PMS/stock/templates/stock/recent_history.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block title %}
異動紀錄
{% endblock %}
{% block css%}

{% endblock css %}
{% block js %}
<script>
$(function (){
    storage_obj = $("#id_storage")
    location_obj = $("#id_location");
    bin_obj = $("#id_bin");
    changeStorageSelect = function(storage_code, obj)
    {
        $.get('/stock/location_api/'+storage_code, function (data){
            $.each(data, function(index, item){
                obj.append('<option value="' + item.location_code + '">' + item.location_name + '</option>')
            })
        })
    }

    changeLocationSelect = function(location_code, obj)
    {
        $.get('/stock/bin_api/'+location_code, function (data){
            $.each(data, function(index, item){
                obj.append('<option value="' + item.bin_code + '">' + item.bin_name + '</option>')
            })
        })
    }

    storage_obj.change(function() {
        location_obj.empty().append("<option value=''>---------</option>");
        changeStorageSelect(this.value, location_obj)
    })

    location_obj.change(function() {
        bin_obj.empty().append("<option value=''>---------</option>");
        changeLocationSelect(this.value, bin_obj)
    })
})
</script>
{% endblock js %}
{% block ready %}
$("#search_tb").bootstrapTable('destroy').bootstrapTable({
    height: 600,
    fixedColumns: true,
    fixedNumber: 1,
    showToggle: false,
});
{% endblock ready %}
{% block content %}
<div class="p-3">
    <form action="{% url 'recent_history' %}" method="post" class="form-group font-weight-bold align-middle" id="import_form" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
    {% if hists %}
    <div class="table-responsive">
        <table id="search_tb">
            <thead>
                <tr>
                    <th class="text-center">儲格</th>
                    <th class="text-center">料號</th>
                    <th class="text-center">物料說明</th>
                    <th class="text-center">MVT</th>
                    <th class="text-center">說明</th>
                    <th class="text-center">+</th>
                    <th class="text-center">-</th>
                    <th class="text-center">數量</th>
                    <th class="text-center">單位</th>
                    <th class="text-center">異動人員</th>
                    <th class="text-center">異動日期</th>
                </tr>
            </thead>
            <tbody>
                {% for hist in hists %}
                    <tr>
                        <td style="text-align: center;">{{ hist.bin.bin_name }}</td>
                        <td style="text-align: center;">{{ hist.item.item_code }}</td>
                        <td style="text-align: center;">{{ hist.item.spec }}</td>
                        <td style="text-align: center;">{{ hist.mvt }}</td>
                        <td style="text-align: center;">{{ hist.desc }}</td>
                        <td style="text-align: right;">+ {{ hist.plus_qty }}</td>
                        <td style="text-align: right;">- {{ hist.minus_qty }}</td>
                        <td style="text-align: right;">{{ hist.remain_qty }}</td>
                        <td style="text-align: center;">{{ hist.item.unit }}</td>
                        <td style="text-align: center;">{{ hist.create_by }}</td>
                        <td style="text-align: center;">{{ hist.create_at|date:"Y/m/d H:i" }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>
{% endblock %}

src/PMS/stock/templates/stock/search.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="row p-3">
    <div class="col-1"></div>
    <div class="col-10">

    </div>
    <div class="col-1"></div>
</div>
{% endblock %}
{% block js %}

{% endblock js %}

src/PMS/stock/templates/stock/stock_in.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="row p-3">
    <div class="col-1"></div>
    <div class="col-10">
        <div class="row">
            <div class="col p-3" style="font-size: 1.5em;text-align: center;">入庫單</div>
        </div>
        <form id="form" action="{% url 'stock_in' %}" method="post">
            {% csrf_token %}
            {% crispy form %}
            <div class="item_list">
                <table class="table table-bordered table-striped">
                    <thead class="table-info">
                        <tr>
                            <th style="width: 10%;text-align: center;">物品類別</th>
                            <th style="width: 45%">品名</th>
                            <th style="width: 10%;text-align: center;">數量</th>
                            <th style="width: 10%;text-align: center;">單位</th>
                            <th style="width: 10%;text-align: center;">儲格</th>
                            <th style="width: 20%">備註</th>
                            <th style="width: 5%"></th>
                        </tr>
                    </thead>
                    <tbody id="item_list">

                    </tbody>
                </table>
            </div>
            <hr />
            <div style="text-align: center" class="p-3">
                <input type="hidden" id="hidItem_list" name="hidItem_list" />
                <input type="submit" value="過帳" class='btn btn-info' onclick="return validation()" />
            </div>
        </form>
    </div>
    <div class="col-1"></div>
</div>
{% endblock %}
{% block js %}
<script>
    //送出時驗證
    function validation() {
        if(list.length == 0) {
            alert("請輸入品項");
            return false;
        }

        return confirm('確認資料是否正確')
    }

    function item_popup() {
        x = window.open("/stock/item_search_popup/","popup_page","location=1,status=1,scrollbars=1,  width=1000,height=1000")
        x.moveTo(0, 0);
    }

    function bin_popup() {
        x = window.open("/stock/bin_search_popup/","popup_page","location=1,status=1,scrollbars=1,  width=1000,height=1000")
        x.moveTo(0, 0);
    }

    //Return Item
    return_item = function(item_code) {
        $("#id_item_code").val(item_code);
    }

    //Return Bin
    return_bin = function(bin_code) {
        $("#id_bin_code").val(bin_code);
    }

    var list = [];

    refresh_table = function(list) {
        $("#item_list").html('');
        var tmp_btn = "<button type='button' class='btn btn-danger' onclick=\"remove_item('{0}')\">移除</button>";
        var row = "<tr><td>{0}</td><td>{1}</td><td style='text-align:center'>{2}</td><td style='text-align:center'>{3}</td><td style='text-align:center'>{4}</td><td>{5}</td><td>{6}</td></tr>";
        $.each(list, function(index, item){
            remove_btn = String.format(tmp_btn, item.spec);
            tmp_row = String.format(row, item.item_code, item.spec, item.qty, item.unit, item.bin_name, item.comment, remove_btn);
            $("#item_list").append(tmp_row);
        })
        $("#hidItem_list").val(JSON.stringify(list));
    }

    //Get Item Info
    get_item_info = function() {
        var item = "";
        var item_code = $("#id_item_code").val();
        $.ajax({
            url: '{% url 'stock_get_item_info' %}', type: 'post',
            dataType: 'json',
            async: false,
            data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "item_code": item_code},
            success: function(data) {
                if(data.length > 0){
                    item = data[0];
                }
            }
        });
        return item;
    }

    //Get Item Info
    get_bin_info = function() {
        var bin = "";
        var bin_code = $("#id_bin_code").val();
        $.ajax({
            url: '{% url 'stock_get_bin_info' %}', type: 'post',
            dataType: 'json',
            async: false,
            data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "bin_code": bin_code},
            success: function(data) {
                if(data.length > 0){
                    bin = data[0];
                }
            }
        });
        return bin;
    }

    //刪除品項
    remove_item = function(spec) {
        var tmp_list = [];
        list.forEach(function(item) {
            if(item.spec != spec){
                tmp_list.push(item);
            }
        });
        list = tmp_list;
        refresh_table(list);
    }

    //新增品項
    add_item = function() {
        var item_code = $("#id_item_code").val();
        var valid = true;

        list.forEach(function(list_item) {
            if(list_item.item_code == item_code){
                valid = false;
            }
        });

        if(valid){
            item = get_item_info();
            if(item.item_code == undefined) {
                valid = false;
                alert("找不到料號");
                return false;
            }
        }

        if(valid){
            bin = get_bin_info();
            if(bin.bin_code == undefined) {
                valid = false;
                alert("找不到儲格");
                return false;
            }
        }

        if(valid){
            item.qty = $("#id_qty").val();
            item.comment = $("#id_comment").val();
            item.bin_code = bin.bin_code;
            item.bin_name = bin.bin_name;
            list.push(item);

            $("#id_item_code").val('');
            $("#id_qty").val('1');
            $("#id_bin_code").val('');
            $("#id_comment").val('');

        }else{
            alert("清單已存在");
        }
        refresh_table(list);
    }


</script>
{% endblock js %}
{% block css %}
<style>
.item_list {
    background: #ffffe7;
    border-color: #f7e1b5;
    border-width: 1px;
    border-style: dashed solid;
}
</style>
{% endblock css %}

src/PMS/stock/templates/stock/stock_search.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block title %}
庫存查詢
{% endblock %}
{% block css%}

{% endblock css %}
{% block js %}
<script>
$(function (){
    storage_obj = $("#id_storage")
    location_obj = $("#id_location");
    bin_obj = $("#id_bin");
    changeStorageSelect = function(storage_code, obj)
    {
        $.get('/stock/location_api/'+storage_code, function (data){
            $.each(data, function(index, item){
                obj.append('<option value="' + item.location_code + '">' + item.location_name + '</option>')
            })
        })
    }

    changeLocationSelect = function(location_code, obj)
    {
        $.get('/stock/location_bin_api/'+location_code, function (data){
            $.each(data, function(index, item){
                obj.append('<option value="' + item.bin_code + '">' + item.bin_name + '</option>')
            })
        })
    }

    storage_obj.change(function() {
        location_obj.empty().append("<option value=''>---------</option>");
        changeStorageSelect(this.value, location_obj)
    })

    location_obj.change(function() {
        bin_obj.empty().append("<option value=''>---------</option>");
        changeLocationSelect(this.value, bin_obj)
    })

})

function history(keyword) {
    $("#keyword").val(keyword);
    $("#history_form").submit();
}

function export_excel() {
    {% if page_results %}
    $('#form').attr('action', '{% url 'stock_search_excel' %}');
    $('#form').submit();
    $("body").loading('stop');
    {% else %}
    alert("無查詢結果");
    {% endif %}
}

</script>
{% endblock js %}
{% block ready %}

{% endblock ready %}
{% block content %}
<div class="p-3">
    <form id="history_form" action="{% url 'stock_history' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="keyword" id="keyword">
    </form>
    <form action="{% url 'stock_search_action' %}" method="post" class="form-group font-weight-bold align-middle" id="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
    {% if page_results %}
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th style="text-align: center">Storage</th>
                <th style="text-align: center">Location</th>
                <th style="text-align: center">儲格</th>
                <th style="text-align: center">料號</th>
                <th>物料說明</th>
                <th style="text-align: center">庫存數量</th>
                <th style="text-align: center">單位</th>
                <th style="text-align: center">異動日期</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for stock in page_results %}
                <tr>
                    <td style="text-align: center">{{ stock.bin.location.storage.storage_code }}</td>
                    <td style="text-align: center">{{ stock.bin.location.location_name }}</td>
                    <td style="text-align: center">{{ stock.bin.bin_name }}</td>
                    <td style="text-align: center">{{ stock.item.item_code }}</td>
                    <td>{{ stock.item.spec }}</td>
                    <td style="text-align: right">{{ stock.qty }}</td>
                    <td style="text-align: center">{{ stock.item.unit }}</td>
                    <td style="text-align: center">{{ stock.update_at|date:"Y/m/d" }}</td>
                    <td style="text-align: center"><input type="button" onclick="history('{{ stock.item.item_code }}')" value="異動紀錄"></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% include "bases/paginating.html" %}
    <span>總筆數：{{ row_count }}</span>
    {% endif %}
</div>
{% endblock %}

src/PMS/stock/templates/stock/stockout_search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/PMS/stock/templates/stock/storage_edit.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block js %}
<script>
function cancel() {
    $("#post_form").submit();
}
</script>
{% endblock js %}
{% block content %}
<form id="post_form" action="{% url 'location_setting' %}" method="post">
{% csrf_token %}
</form>
<div class="pt-3">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <form id="post_form" action="{% url 'storage_edit' %}" method="post">
                {% csrf_token %}
                {% crispy form %}
                <div style="text-align: center" class="p-3">
                    <input type="submit" value="儲存" class='btn btn-info' />
                    <input type="hidden" value="edit" name="action" />
                    <input type="hidden" value="{{ pk }}" name="pk" />
                    <input type="button" class="btn btn-info" value="取消" onClick="cancel();">
                </div>
            </form>
        </div>
        <div class="col-1"></div>
    </div>
</div>
{% endblock %}