src/PMS/PMS/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

from borrow.ser_views import BorrowByViewSet
from bugs.ser_views import BugByPViewSet
from problems.ser_views import ProblemByPViewSet, ProblemByRViewSet, ProblemByBViewSet
from bases.views import index
from django.conf.urls.static import static
from django.conf import settings

from requests.ser_views import SubRequestViewSet, RequestByPViewSet

router = DefaultRouter()
router.register(r'requests/(?P<request_id>\d+)/requests', SubRequestViewSet)
router.register(r'requests/(?P<request_id>\w+)/problems', ProblemByRViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/requests', RequestByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/problems', ProblemByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/bugs', BugByPViewSet)
router.register(r'bugs/(?P<bug_id>\d+)/problems', ProblemByBViewSet)
router.register(r'borrow', BorrowByViewSet)

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^stock/', include('stock.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^borrow/', include('borrow.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^requests/', include('requests.urls')),
    url(r'^problems/', include('problems.urls')),
    url(r'^home', include('bases.urls')),
    url(r'^bugs/', include('bugs.urls')),
    url(r'^tests/', include('tests.urls')),
    url(r'^helpdesk/', include('helpdesk.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
    url(r'^users/', include('users.urls')),
)

src/PMS/borrow/urls.py
from django.urls import re_path as url
from borrow.views import apply, get_asset_api, find_asset_api, record, get_borrow_item_api, detail, \
    update, form_delete, item_delete

urlpatterns = [
    url(r'^apply/', apply, name='apply'),
    url(r'^record/', record, name='record'),
    url(r'^detail/(?P<form_no>\d+)/', detail, name='detail'),
    url(r'^update/(?P<pk>\d+)/$', update, name='borrow_update'),
    url(r'^item_delete/(?P<form_no>\d+)/(?P<asset_id>\d+)/', item_delete, name='borrow_item_delete'),
    url(r'^form_delete/(?P<form_no>\d+)/', form_delete, name='form_delete'),
    url(r'^(?P<pk>\d+)/item/', get_borrow_item_api, name='get_borrow_item_api'),
    url(r'^get_asset_api/', get_asset_api, name='get_asset_api'),
    url(r'^find_asset_api/', find_asset_api, name='find_asset_api'),
]

src/PMS/borrow/models.py
from django.db import models
from django.conf import settings
from assets.models import Asset
from datetime import datetime

class Borrow(models.Model):
    form_no = models.AutoField(primary_key=True)
    app_dept = models.CharField(max_length=50, blank=False, null=False)
    app_user = models.CharField(max_length=50, blank=False, null=False)
    comment = models.CharField(max_length=500, blank=False, null=False)
    apply_date = models.CharField(max_length=10, blank=False, null=False)
    expect_date = models.CharField(max_length=10, blank=False, null=False)
    lend_date = models.CharField(max_length=10, blank=True, null=True)
    lend_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='lend_owner', null=True)
    return_date = models.CharField(max_length=10, blank=True, null=True)
    return_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='return_owner', null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='borrow_update_by', null=True)
    admin_comment = models.CharField(max_length=500, blank=False, null=False)
    finished = models.BooleanField(default=False)


class BorrowItem(models.Model):
    borrow = models.ForeignKey(Borrow, related_name='borrow_item', on_delete=models.CASCADE)
    asset = models.ForeignKey(Asset, related_name='borrow_asset', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.asset.label_no + " " + self.asset.model + " " + self.asset.desc


class BPMDept(models.Model):
    class Meta:
        managed = False

    dept_no = models.CharField(max_length=50, blank=False, null=False, unique=True)
    dept_name = models.CharField(max_length=50, blank=False, null=False, unique=True)

    def __str__(self):
        return self.dept_name


class BPMUser(models.Model):
    class Meta:
        managed = False

    user_no = models.CharField(max_length=50, blank=False, null=False, unique=True)
    user_name = models.CharField(max_length=50, blank=False, null=False, unique=True)

    def __str__(self):
        return self.user_name

src/PMS/borrow/forms.py
from datetime import datetime

from django import forms
from .models import Borrow, BPMDept, BPMUser
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML, Fieldset
from bootstrap_datepicker_plus.widgets import DatePickerInput


class BorrowForm(forms.ModelForm):
    class Meta:
        model = Borrow
        fields = (
            'apply_date', 'expect_date', 'comment')

    comment = forms.CharField(required=True, label="借用原因")
    apply_date = forms.CharField(required=True, label="借用日期")
    expect_date = forms.CharField(required=True, label="預計歸還日期")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True

        self.helper.layout = Layout(
            Div(
                Div('apply_date', css_class='col-md-6'),
                Div('expect_date', css_class='col-md-6'),
                css_class='row'),
            Div(
                Div('comment', css_class='col-md-12'),
                css_class='row'),
        )

        self.fields['apply_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

        self.fields['expect_date'].widget = DatePickerInput(
            attrs={'value': datetime.now().strftime('%Y-%m-%d')},
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

class BorrowAdminForm(forms.ModelForm):
    class Meta:
        model = Borrow
        fields = (
            'lend_date', 'return_date', 'admin_comment')

    admin_comment = forms.CharField(required=False, label="備註")
    lend_date = forms.CharField(required=False, label="實際借出日期")
    return_date = forms.CharField(required=False, label="實際歸還日期")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True

        self.helper.layout = Layout(
            Div(
                Div('lend_date', css_class='col-md-6'),
                Div('return_date', css_class='col-md-6'),
                css_class='row'),
            Div(
                Div('admin_comment', css_class='col-md-12'),
                css_class='row'),
        )

        self.fields['lend_date'].widget = DatePickerInput(
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

        self.fields['return_date'].widget = DatePickerInput(
            options={
                "format": "YYYY-MM-DD",
                "showClose": False,
                "showClear": False,
                "showTodayButton": False,
            }
        )

src/PMS/borrow/views.py
from django.urls import reverse
from assets.models import AssetType, Asset, AssetStatus
from borrow.forms import BorrowForm, BorrowAdminForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from borrow.models import Borrow, BorrowItem


# bootstrap sub table
from users.models import Unit, CustomUser


def get_borrow_item_api(request, pk):
    _json = []
    items = BorrowItem.objects.filter(borrow=pk)
    for item in items:
        _json.append({"type_name": item.asset.type.type_name, "asset_no": item.asset.asset_no, "model": item.asset.model, "desc": item.asset.desc})
    return JsonResponse(_json, safe=False)


def find_asset_api(request):
    if request.method == 'POST':
        asset_no = request.POST.get('asset_no')
        asset = Asset.objects.get(asset_no=asset_no)
        name = "({status}){asset_no}　{model}　{desc}".format(status=asset.status, asset_no=asset.asset_no,
                                                            model=asset.model, desc=asset.desc)
        html = """[{{\"value\":\"{value}\", \"name\":\"{name}\"}}]""".format(value=asset_no, name=name)
    return JsonResponse(html, safe=False)


def get_asset_api(request):
    if request.method == 'POST':
        typeId = request.POST.get('typeId')
        assets = Asset.objects.filter(type=typeId, status__in=(9, 4))  # 狀態9可出借, 狀態4出借中
        html = ""

        for asset in assets:
            name = "({status}){asset_no}　{model}　{desc}".format(status=asset.status, asset_no=asset.asset_no, model=asset.model, desc=asset.desc)
            html += """<option value="{value}">{name}</option>""".format(value=asset.asset_no, name=name)
    return JsonResponse(html, safe=False)


def createDeptOption():
    rows = Unit.objects.all()
    html = "<option value="" selected>---------</option>"

    for row in rows:
        html += """<option value="{value}">{name}</option>""".format(value=row.id, name=row.unitName)
    return html


def createAssetTypeOption():
    status = AssetStatus.objects.get(status_name="可出借")
    assets = Asset.objects.filter(status=status).values("type").distinct()
    types = AssetType.objects.filter(id__in=assets)
    html = "<option value="" selected>---------</option>"

    for type in types:
        html += """<option value="{value}">{name}</option>""".format(value=type.id, name=type.type_name)
    return html


def record(request):
    return render(request, 'borrow/record.html', locals())


def apply(request):
    if request.method == 'POST':
        apply_dept = request.POST.get('apply_dept')
        apply_user = request.POST.get('apply_user')
        apply_date = request.POST.get('apply_date')
        expect_date = request.POST.get('expect_date')
        comment = request.POST.get('comment')
        borrow_list = request.POST.get('hidBorrowList')

        try:
            borrow = Borrow()
            borrow.app_dept = Unit.objects.get(id=apply_dept)
            borrow.app_user = CustomUser.objects.get(id=apply_user)
            borrow.comment = comment
            borrow.apply_date = apply_date
            borrow.expect_date = expect_date
            borrow.save()

            assets = borrow_list.split(",")
            for asset in assets:
                if asset:
                    item = BorrowItem()
                    item.borrow = borrow
                    asset = Asset.objects.get(asset_no=asset)
                    item.asset = asset
                    item.save()

                    asset.status = AssetStatus.objects.get(status_name='出借中')
                    asset.save()
        except Exception as e:
            print(e)

        return redirect(reverse('record'))

    form = BorrowForm()
    dept_options = createDeptOption()
    asset_type_options = createAssetTypeOption()
    return render(request, 'borrow/application.html', locals())


def update(request, pk):
    if request.method == 'POST':
        lend_date = request.POST.get('lend_date')
        return_date = request.POST.get('return_date')
        borrow = Borrow.objects.get(form_no=pk)
        items = BorrowItem.objects.filter(borrow=borrow)

        if borrow.finished is False:
            if lend_date and not return_date:
                borrow.lend_owner = request.user
                for item in items:
                    asset = Asset.objects.get(id=item.asset.id)
                    asset.status = AssetStatus.objects.get(id=4)  # 出借中
                    asset.save()

            if return_date:
                borrow.return_owner = request.user
                for item in items:
                    asset = Asset.objects.get(id=item.asset.id)
                    asset.status = AssetStatus.objects.get(id=9)  # 可出借
                    asset.save()

        form = BorrowAdminForm(request.POST, instance=borrow)
        if form.is_valid():
            tmp_form = form.save(commit=False)
            tmp_form.save()
    return render(request, 'borrow/record.html', locals())


def detail(request, form_no):
    borrow = Borrow.objects.get(form_no=form_no)
    items = borrow.borrow_item.all()
    admin_form = BorrowAdminForm(instance=borrow)
    return render(request, 'borrow/detail.html', locals())


def form_delete(request, form_no):
    borrow = Borrow.objects.get(form_no=form_no)
    for item in borrow.borrow_item.all():
        asset = Asset.objects.get(id=item.asset_id)
        asset.status = AssetStatus.objects.get(id=9)  # 可出借
        asset.save()
    borrow.delete()
    return render(request, 'borrow/record.html', locals())


def item_delete(request, form_no, asset_id):
    borrow = Borrow.objects.get(form_no=form_no)
    asset = Asset.objects.get(id=asset_id)
    asset.status = AssetStatus.objects.get(id=9)  # 可出借
    asset.save()

    item = BorrowItem.objects.get(asset=asset)
    item.delete()
    return render(request, 'borrow/record.html', locals())

src/PMS/borrow/templates/borrow/application.html
{% extends 'borrow/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    資訊借物申請單
{% endblock %}
{% block sub_container %}
<div class="row">
    <div class="col-1"></div>
    <div class="col-10">
        <div style="text-align: center;font-size: 1.2em">資訊設備借用申請單</div>
        <hr />
        <form method="post" action="{% url 'apply' %}">
            {% csrf_token %}
            <input type="hidden" name="hidBorrowList" id="hidBorrowList" value="" />
            <div class="row">
                <div class="col-6">
                    <div id="div_id_apply_dept" class="form-group">
                        <label for="id_apply_dept" class="requiredField">
                            申請部門<span class="asteriskField">*</span>
                        </label>
                        <select name="apply_dept" class="select custom-select" id="id_apply_dept" required="" onchange="dept_change();">
                            {{ dept_options | safe }}
                        </select>
                    </div>
                </div>
                <div class="col-6">
                    <div id="div_id_apply_user" class="form-group">
                        <label for="id_apply_user" class="requiredField">
                            申請人<span class="asteriskField">*</span>
                        </label>
                        <select name="apply_user" class="select custom-select" id="id_apply_user" required="">
                            <option value="" selected>---------</option>
                        </select>
                    </div>
                </div>
            </div>
            {% crispy form %}
            <hr />
            <div class="row">
                <div class="col-5">
                    <div id="div_id_asset_type" class="form-group">
                        <label for="id_asset_type">
                            物品類別
                        </label>
                        <select name="asset_type" class="select custom-select" id="id_asset_type" onchange="asset_type_change();">
                            {{ asset_type_options | safe }}
                        </select>
                    </div>
                </div>
                <div class="col-2"></div>
                <div class="col-5">
                    <div id="div_id_asset" class="form-group">
                        <label for="id_asset">
                            標籤編號
                        </label>
                        <div class="row">
                            <div class="col">
                                <input type="text" name="asset_no" class="textinput textInput form-control" id="id_asset_no">
                            </div>
                            <div class="col">
                                <input class="btn btn-success" type="button" onclick="asset_no_click()" value="放入清單" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-5">
                    <div id="div_id_asset_list" class="form-group">
                        <label for="id_asset_list">
                            請選擇要借的物品
                        </label>
                        <select id="asset_list" class="select custom-select" multiple aria-label="multiple select" style="height: 300px">
                        </select>
                    </div>
                </div>
                <div class="col-2 pt-4" style="text-align: center">
                    <input class="btn btn-success mt-3" type="button" value="=>" style="width: 100px" onclick="move1()" /><br />
                    <input class="btn btn-success mt-3" type="button" value="<=" style="width: 100px" onclick="move2()" /><br />
                    <input class="btn btn-success mt-3" type="button" value="<<" style="width: 100px" onclick="clean()" />
                </div>
                <div class="col-5">
                    <div id="div_id_borrow_list" class="form-group">
                        <label for="id_borrow_list">
                            借物清單
                        </label>
                        <select id="borrow_list" name="borrow_list" class="select custom-select" multiple aria-label="multiple select" style="height: 300px">
                        </select>
                    </div>
                </div>
            </div>
            <hr />
            <div class="pb-4" style="text-align: center;">
              <input class="btn btn-success" type="submit" value="借出" />
            </div>
        </form>
    </div>
    <div class="col-1"></div>
</div>
{% endblock sub_container %}

{% block js %}
<script>
    function asset_no_click() {
        $.ajax({
            url: '{% url 'find_asset_api' %}', type: 'post',
            dataType: 'json',
            data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "asset_no": $("#id_asset_no").val()},
            success: function(data) {
                obj = eval(data);
                const select_2 = document.getElementById("borrow_list");
                let new_option = document.createElement('option');
                new_option.value = obj[0].value
                new_option.innerHTML = obj[0].name;
                select_2.appendChild(new_option);
            }
        });
    }


    function dept_change() {
        $.ajax({
            url: '{% url 'get_deptuser_api' %}', type: 'post',
            dataType: 'json',
            data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "unit": $("#id_apply_dept :selected").val()},
            success: function(data) {
                $("#id_apply_user").html(data);
            }
        });
    }

    function asset_type_change() {
        $.ajax({
            url: '{% url 'get_asset_api' %}', type: 'post',
            dataType: 'json',
            data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "typeId": $("#id_asset_type :selected").val()},
            success: function(data) {
                $("#asset_list").html(data);
            }
        });
    }

    function move1() {
        const select_1 = document.getElementById("asset_list");
        const select_2 = document.getElementById("borrow_list");

        if(select_1.selectedIndex !== -1) {
            const selected_option = select_1.options[select_1.selectedIndex];

            let new_option = document.createElement('option');
            new_option.value = selected_option.value
            new_option.innerHTML = selected_option.innerHTML;
            select_2.appendChild(new_option);

            select_1.options.remove(select_1.selectedIndex)
        }
        updateList();

    }

    function move2(){
        const select_1 = document.getElementById("asset_list");
        const select_2 = document.getElementById("borrow_list");

        if(select_2.selectedIndex !== -1) {
            const selected_option = select_2.options[select_2.selectedIndex];

            let new_option = document.createElement('option');
            new_option.value = selected_option.value
            new_option.innerHTML = selected_option.innerHTML;
            select_1.appendChild(new_option);

            select_2.options.remove(select_2.selectedIndex)
        }
        updateList();
    }

    function clean() {
        $("#borrow_list").empty();
        asset_type_change();
        updateList();
    }

    function updateList() {
        var x = document.getElementById('borrow_list');
        var val = "";
        for (var i = 0; i < x.length; i++) {
            val +=x[i].value + ",";
        }
        document.getElementById('hidBorrowList').value = val;
    }



</script>

{% endblock js %}
{% block css %}
<style type="text/css">
#borrow_list {
    background: #ffffe7;
}
</style>
{% endblock css %}

src/PMS/borrow/templates/borrow/base.html
{% extends "bases/base.html" %} {% load static %}

{% block title %} {{ block.super}} {% endblock title %}

{% block css %}

{% endblock css %}

{% block container %}
<div class="card-header">
    <div class="row">
        <div class="col">
            <button type="button" class="btn btn-success" onclick="location.href='{% url 'apply' %}'">申請填寫</button>
            <button type="button" class="btn btn-success" onclick="location.href='{% url 'record' %}'">借出紀錄</button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-1"></div>
    <div class="col-10 pt-3">
        {% block sub_container %}
        {% endblock sub_container %}
    </div>
    <div class="col-1"></div>
</div>

{% endblock container %}

{% block js %}

{% endblock js %}

src/PMS/borrow/templates/borrow/detail.html
{% extends 'borrow/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    資訊借物申請單
{% endblock %}
{% block sub_container %}
<fieldset>
    <legend>借用資訊</legend>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row">
                <div class="col-2 p-2" style="text-align:right;">申請部門：</div>
                <div class="col-2 p-2 content">{{ borrow.app_dept }}</div>
                <div class="col-2 p-2" style="text-align:right;">申請人：</div>
                <div class="col-2 p-2 content">{{ borrow.app_user }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-2 p-2" style="text-align:right;">申請日期：</div>
                <div class="col-2 p-2 content">{{ borrow.apply_date|default:"" }}</div>
                <div class="col-2 p-2" style="text-align:right;">預計歸還日期：</div>
                <div class="col-2 p-2 content">{{ borrow.expect_date|default:"" }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-2 p-2" style="text-align:right;">說明：</div>
                <div class="col-2 p-2 content">{{ borrow.comment }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-2 p-2" style="text-align:right;">交付：</div>
                <div class="col-2 p-2 content">{{ borrow.lend_owner|default:"" }}</div>
                <div class="col-2 p-2" style="text-align:right;">交付日期：</div>
                <div class="col-2 p-2 content">{{ borrow.lend_date|default:"" }}</div>
            </div>
        </li>
        <li class="list-group-item">
            <div class="row">
                <div class="col-2 p-2" style="text-align:right;">歸還：</div>
                <div class="col-2 p-2 content">{{ borrow.return_owner|default:"" }}</div>
                <div class="col-2 p-2" style="text-align:right;">歸還日期：</div>
                <div class="col-2 p-2 content">{{ borrow.return_date|default:"" }}</div>
            </div>
        </li>
    </ul>
</fieldset>
<fieldset>
    <legend>物品資訊</legend>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="row">
                <table class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>標籤編號</th>
                            <th>資產類別</th>
                            <th>品牌</th>
                            <th>物品</th>
                            <th>備註</th>
                            <th>刪除</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for item in items %}
                        <tr>
                            <td>{{ item.asset.label_no }}</td>
                            <td>{{ item.asset.type }}</td>
                            <td>{{ item.asset.brand }}</td>
                            <td>{{ item.asset.model }}</td>
                            <td>{{ item.asset.desc }}</td>
                            <td style="text-align: center"><a href="/borrow/item_delete/{{ borrow.form_no }}/{{ item.asset.pk }}/" class="btn btn-danger" onclick="return confirm('Are you sure?')">刪除</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </li>
    </ul>
</fieldset>
{% if user.is_authenticated %}
<fieldset>
    <legend>管理者</legend>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="p-3">
                <form method="post" action="{% url 'borrow_update' borrow.pk %}">
                  {% csrf_token %}
                  {% crispy admin_form %}
                    <div class="pb-4" style="text-align: center;">
                        <input class="btn btn-success" type="submit" value="修改" />
                        <a href="{% url 'form_delete' borrow.form_no %}" class="btn btn-danger" onclick="return confirm('Are you sure?')">刪除</a>
                    </div>
                </form>
            </div>
        </li>
    </ul>
</fieldset>
{% endif %}
<div style="text-align:left;color:#EEE">
    最後修改：{{ borrow.update_at|date:'Y-m-d' }} {{ borrow.update_by }}
</div>

{% endblock sub_container %}

{% block js %}

{% endblock js %}
{% block css %}

{% endblock css %}