src/PMS/PMS/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from rest_framework.routers import DefaultRouter

from borrow.ser_views import BorrowByViewSet
from bugs.ser_views import BugByPViewSet
from problems.ser_views import ProblemByPViewSet, ProblemByRViewSet, ProblemByBViewSet
from bases.views import index
from django.conf.urls.static import static
from django.conf import settings

from requests.ser_views import SubRequestViewSet, RequestByPViewSet

router = DefaultRouter()
router.register(r'requests/(?P<request_id>\d+)/requests', SubRequestViewSet)
router.register(r'requests/(?P<request_id>\w+)/problems', ProblemByRViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/requests', RequestByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/problems', ProblemByPViewSet)
router.register(r'projects/(?P<project_id>\d+)/(?P<user_id>\d+)/bugs', BugByPViewSet)
router.register(r'bugs/(?P<bug_id>\d+)/problems', ProblemByBViewSet)
router.register(r'borrow', BorrowByViewSet)

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^stock/', include('stock.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^production/', include('production.urls')),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^borrow/', include('borrow.urls')),
    url(r'^projects/', include('projects.urls')),
    url(r'^requests/', include('requests.urls')),
    url(r'^problems/', include('problems.urls')),
    url(r'^home', include('bases.urls')),
    url(r'^bugs/', include('bugs.urls')),
    url(r'^tests/', include('tests.urls')),
    url(r'^helpdesk/', include('helpdesk.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^api/', include(router.urls)),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
    url(r'^users/', include('users.urls')),
)

src/PMS/inventory/urls.py
from django.urls import re_path as url
from inventory.views import main, apply, TypeAPI, ItemAPI, detail, agree, apply_list, approve, reject, import_excel, \
    statistic, change_status, delete, mail_reject, mail_agree, recieved, pr_apply, search, item_list, item_detail, \
    item_update, item_create, setting, export_form_xls, CategoryAPI, template_edit

urlpatterns = [
    url(r'^main/', main, name='inv_main'),
    url(r'^apply/', apply, name='inv_apply'),
    url(r'^pr_apply/', pr_apply, name='inv_pr_apply'),
    url(r'^typeapi/(?P<category_id>\d+)', TypeAPI, name='catogory_typeapi'),
    url(r'^itemapi/', ItemAPI, name='catogory_itemapi'),
    url(r'^detail/(?P<pk>\w+)/$', detail, name='inv_detail'),
    url(r'^delete/(?P<pk>\w+)/$', delete, name='inv_delete'),
    url(r'^agree/(?P<key>\w+)/$', agree, name='inv_agree'),
    url(r'^reject/(?P<key>\w+)/$', reject, name='inv_reject'),
    url(r'^list/', apply_list, name='inv_list'),
    url(r'^approve/', approve, name='inv_approve'),
    url(r'^import/', import_excel, name='inv_import'),
    url(r'^statistic/', statistic, name='inv_statistic'),
    url(r'^change_status/', change_status, name='inv_change_status'),
    url(r'^mail_reject/(?P<key>\w+)/$', mail_reject, name='inv_mail_reject'),
    url(r'^mail_agree/(?P<key>\w+)/$', mail_agree, name='inv_mail_agree'),
    url(r'^recieved/(?P<pk>\w+)/$', recieved, name='inv_recieved'),
    url(r'^search/', search, name='inv_search'),
    url(r'^item_list/', item_list, name='item_list'),
    url(r'^item_detail/(?P<pk>\w+)/$', item_detail, name='item_detail'),
    url(r'^item_update/(?P<pk>\d+)/$', item_update, name='item_update'),
    url(r'^item_create/', item_create, name='item_create'),
    url(r'^setting/', setting, name='inv_setting'),
    url(r'^export_form_xls/', export_form_xls, name='export_form_xls'),
    url(r'^categoryapi/(?P<family_id>\d+)', CategoryAPI, name='item_categoryapi'),
    url(r'^typeapi/(?P<category_id>\d+)', TypeAPI, name='item_typeapi'),
    url(r'^template_edit/', template_edit, name='template_edit'),
]

src/PMS/inventory/models.py
from django.contrib.auth.models import Group
from django.db import models
from django.conf import settings
from datetime import datetime
from django.urls import reverse
from users.models import Unit


class FormStatus(models.Model):
    status_name = models.CharField(max_length=50, blank=False, null=False)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='form_status_create_by')  # 建立者

    def __str__(self):
        return self.status_name


class ItemFamily(models.Model):
    family_code = models.CharField(max_length=2, blank=False, null=False)
    family_name = models.CharField(max_length=50, blank=False, null=False)
    perm_group = models.ForeignKey(Group, on_delete=models.DO_NOTHING, related_name='family_group', null=True,
                                   blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='item_family_create_by')  # 建立者
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='item_family_update_by')

    def __str__(self):
        return self.family_name


class ItemCategory(models.Model):
    family = models.ForeignKey(ItemFamily, related_name='category_family', on_delete=models.DO_NOTHING)
    catogory_code = models.CharField(max_length=2, blank=False, null=False)
    category_name = models.CharField(max_length=50, blank=False, null=False)
    manual = models.BooleanField(default=False)
    enable = models.BooleanField(default=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='item_category_create_by')  # 建立者
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='item_category_update_by')

    def __str__(self):
        return self.category_name


class ItemType(models.Model):
    category = models.ForeignKey(
        ItemCategory, related_name='type_category', on_delete=models.CASCADE)
    type_code = models.CharField(max_length=2, blank=False, null=False)
    type_name = models.CharField(max_length=50, blank=False, null=False)
    is_attached = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='item_type_create_by')  # 建立者
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='item_type_update_by')

    def __str__(self):
        return self.type_name


class Item(models.Model):
    item_code = models.CharField(max_length=11, blank=False, null=False)
    sap_code = models.CharField(max_length=20, blank=True, null=True)
    vendor_code = models.CharField(max_length=20, blank=True, null=True)
    unit = models.CharField(max_length=10, blank=False, null=False)
    item_type = models.ForeignKey(ItemType, related_name='item_type', on_delete=models.CASCADE)
    spec = models.CharField(max_length=2000, blank=True, null=True)
    price = models.FloatField(default=0)
    enabled = models.BooleanField(default=True)
    is_stock = models.BooleanField(default=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='item_create_by')  # 建立者
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='item_update_by')

    def __str__(self):
        return self.spec

    def get_absolute_url(self):
        return reverse('item_detail', kwargs={'pk': self.pk})

class Pic_attachment(models.Model):
    item = models.ForeignKey('Item', related_name='item_pics', on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/picture/item/')
    description = models.CharField(max_length=50, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='item_pic_create_by')  # 建立者


class AppliedForm(models.Model):
    form_no = models.CharField(max_length=20, primary_key=True)
    unit = models.ForeignKey(Unit, related_name='applied_unit', on_delete=models.DO_NOTHING)
    requester = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='applied_form_requester')
    approver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='applied_form_approver', blank=True, null=True)
    approve_time = models.DateTimeField(null=True)
    apply_date = models.CharField(max_length=10, blank=False, null=False)
    category = models.ForeignKey(ItemCategory, related_name='form_category', on_delete=models.DO_NOTHING)
    status = models.ForeignKey(FormStatus, related_name='form_status', on_delete=models.DO_NOTHING)
    ext_number = models.CharField(max_length=20, blank=True, null=True)
    reason = models.CharField(max_length=2000, blank=True, null=True)
    admin_comment = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='inv_form_create_by')  # 建立者
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='inv_form_update_by')

    def get_absolute_url(self):
        return reverse('inv_detail', kwargs={'pk': self.pk})


class AppliedItem(models.Model):
    applied_form = models.ForeignKey(AppliedForm, related_name='applied_form_item', on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    item_code = models.CharField(max_length=11)
    spec = models.CharField(max_length=200)
    model = models.CharField(max_length=200, blank=True, null=True)
    qty = models.IntegerField(default=0)
    unit = models.CharField(max_length=10)
    comment = models.CharField(max_length=2000, blank=True, null=True)
    received_qty = models.IntegerField(default=0)


class Apply_attachment(models.Model):
    apply = models.ForeignKey('AppliedForm', related_name='apply_files', on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/inventory/apply/%Y/%m/')
    description = models.CharField(max_length=50, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='form_files_create_by')  # 建立者


class Series(models.Model):
    key = models.CharField(max_length=50, blank=False, null=False)
    series = models.IntegerField()
    desc = models.CharField(max_length=50, blank=True, null=True)


class Setting(models.Model):
    attr = models.CharField(max_length=50, blank=False, null=False)
    values = models.CharField(max_length=500, blank=False, null=False)


class Template_attachment(models.Model):
    key_file = models.FileField(upload_to='inventory/template/')
    stamp_file = models.FileField(upload_to='inventory/template/')
    print_file = models.FileField(upload_to='inventory/template/')
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='template_update_by')

src/PMS/inventory/templates/inventory/application.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<form method="post" action="{% url 'inv_apply' %}" enctype="multipart/form-data">
{% csrf_token %}
<div class="p-3">
    {% crispy form %}
    <hr />
    <div class="row">
        <div class="col">
            <input type="button" onclick="popupfunc();" class='btn btn-info m-1' value="請購物品查詢">
        </div>
        <div class="col">
            {% for template in templates %}
            <a href='{{ template.key_file.url }}' id='key_template' class='btn btn-light m-1'>鑰匙申請單範本</a>
            <a href='{{ template.stamp_file.url }}' id='stamp_template' class='btn btn-light m-1'>印章申請單範本</a>
            <a href='{{ template.print_file.url }}' id='card_template' class='btn btn-light m-1'>印刷品申請單範本</a>
            {% endfor %}
        </div>
    </div>
</div>
<div>
    <div class="col">
        <div style="background: #ffffe7">
            <div id="cart_list"></div>
        </div>
    </div>
</div>
<div>
    <div class="col">
        {% crispy attach_form %}
    </div>
</div>
<hr />
<div style="text-align:center;height: 100px">
    <input type="hidden" id="hidCart_list" name="hidCart_list" />
    <input type="submit" value="確認送簽" class='btn btn-info' onclick="return validation()" />
</div>
</form>
{% endblock %}
{% block js %}
<script>
    function open_window(url) {
        window.open(url, "_blank", "toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=500,width=400,height=400");
    }

    function popupfunc() {
        x = window.open("/inventory/search/","popup_page","location=1,status=1,scrollbars=1,  width=1000,height=1000")
        x.moveTo(0, 0);
    }

    function dept_change() {
        $.ajax({
            url: '{% url 'get_deptuser_api' %}', type: 'post',
            dataType: 'json',
            data: {"csrfmiddlewaretoken": "{{ csrf_token }}", "unit": $("#id_unit :selected").val()},
            success: function(data) {
                $("#id_requester").html(data);
            }
        });
    }

    //送出時驗證
    function validation() {
        if(list.length == 0) {
            alert("請選擇請領品項");
            return false;
        }else{
            var tmp="";
            for(var i=0;i<list.length;i++){
                if(tmp=="") tmp = list[i].category;
                if(list[i].category != tmp){
                    alert("同單據物品類別必須相同");
                    return false;
                }
            }
        }

        return confirm('確認資料是否正確')
    }

    changeSelect = function(category_id, asset_type)
    {
        $.get('/inventory/typeapi/'+category_id, function (data){
            $.each(data, function(index, item){
                asset_type.append('<option value="' + item.id + '">' + item.type_name + '</option>')
            })
        })
    }

    var list = [];

    //新增品項
    cart_add = function(category, item_code, spec, unit, pic) {
        var item = {"item_code": item_code, "spec": spec, "qty": 1, "unit": unit, "comment": "", "category": category, "pic": pic};
        var valid = true;
        list.forEach(function(list_item) {
            if(list_item.item_code == item_code){
                valid = false;
            }
        });
        if(valid){
            list.push(item);
        }else{
            alert("清單已存在");
        }
        cart_show(list);
    }

    //新增雜項
    cart_misc_add = function(category, item_code, unit, spec) {
        var item = {"item_code": item_code, "spec": spec, "qty": 1, "unit": unit, "comment": "", "category": category};
        list.push(item);
        cart_show(list);
    }

    //刪除品項
    cart_remove = function(spec) {
        var tmp_list = [];
        list.forEach(function(item) {
            if(item.spec != spec){
                tmp_list.push(item);
            }
        });
        list = tmp_list;
        cart_show(list);
    }

    //單價變動
    cart_qty = function(item_code, qty) {
        list.forEach(function(item) {
            if(item.item_code == item_code){
                item.qty = qty;
            }
        });
        cart_show(list);
    }

    //備註
    cart_comment = function(item_code, comment) {
        list.forEach(function(item) {
            if(item.item_code == item_code){
                item.comment = comment;
            }
        });
        cart_show(list);
    }

    //顯示請購清單
    cart_show = function(data) {
        var tmp_table = "<table class=\"table\"><tr><th width='100px'>物品類別</th><th>品名&規格</th><th width='100px'>數量</th><th width='80px'>單位</th><th>備註</th><th></th></tr>{0}</table>";
        var tmp_item = "<tr><td>{0}</td><td><a href=\"#\" onclick=\"open_window('/media/{1}')\">{2}</a></td><td>{3}</td><td>{4}</td><td>{5}</td><td>{6}</td></tr>";
        var tmp_qty = "<input type=\"text\" class=\"form-control\" value=\"{0}\" onchange=\"cart_qty('{1}', this.value)\">";
        var tmp_comment = "<input type=\"text\" class=\"form-control\" value=\"{0}\" onchange=\"cart_comment('{1}', this.value)\">";
        var tmp_btn = "<button type='button' class='btn btn-danger' onclick=\"cart_remove('{0}')\">移除</button>";
        var temp = "";
        var items = "";
        var remove_btn = "";
        var add_qty = "";
        $("#cart_list").html("");
        $.each(data, function(index, item){
            remove_btn = String.format(tmp_btn, item.spec);
            add_qty = String.format(tmp_qty, item.qty, item.item_code);
            comment = String.format(tmp_comment, item.comment, item.item_code);
            temp = String.format(tmp_item, item.category, item.pic, item.spec, add_qty, item.unit, comment, remove_btn);
            items = items + temp;
        })
        $("#cart_list").append(String.format(tmp_table, items));
        $("#hidCart_list").val(JSON.stringify(list));
    }

    //Ready
    $(function (){
        category = $('#id_category');
        asset_type = $('#id_type');

        changeSelect(0, asset_type);

        category.change(function(){
            asset_type.empty().append('<option value="">---------</option>');
            changeSelect(this.value, asset_type)
        })

        $("#id_keyword").on('keypress', function(e) {
            if(e.which==13) {
                $("#button-id-search").click();
            }
            return false;
        })
    })
</script>
{% endblock js %}

src/PMS/inventory/templates/inventory/approve.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="p-3 table-responsive" style="height:700px; overflow:auto;background-color: #FFFFFF;">
    <table class="table table-bordered table-striped">
        <thead class="thead-dark">
            <tr>
                <th width="5%" style="text-align: center">單號</th>
                <th width="10%" style="text-align: center">申請日期</th>
                <th width="15%" style="text-align: center">申請部門</th>
                <th width="10%" style="text-align: center">申請人</th>
                <th width="25%" style="text-align: center">原因</th>
                <th width="10%" style="text-align: center">狀態</th>
                <th width="10%"></th>
            </tr>
        </thead>
        <tbody>
        {% if list %}
            {% for data in list %}
                <tr>
                    <td style="text-align: center">{{ data.form_no }}</td>
                    <td style="text-align: center">{{ data.apply_date }}</td>
                    <td style="text-align: center">{{ data.unit }}</td>
                    <td style="text-align: center">{{ data.requester }}</td>
                    <td style="text-align: left">{{ data.reason }}</td>
                    <td style="text-align: center">{{ data.status }}</td>
                    <td style="text-align: center"><a href="{% url 'inv_detail' data.form_no %}" class="btn btn-warning">請購明細</a></td>
                </tr>
            {% endfor %}
        {% else %}
            <tr><td colspan="7" align="center">無簽核單據</td></tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}
{% block js %}

{% endblock js %}

src/PMS/inventory/templates/inventory/attachment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/PMS/inventory/templates/inventory/import.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<form action="" method="post" class="form-group font-weight-bold align-middle" id="import_form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card-body">
        <div>請選擇Template檔案(*.xlsx)
            <a href="{% static "inventory/import_template.xlsx" %}" target="_blank">下載範本檔</a>
        </div>
        <div class="row">
            <div id="div_id_files" class="form-group">
                <input name="files1" accept=".xls,.xlsx" class="clearablefileinput" id="id_files" type="file">
                <button type="submit" class="btn btn-primary" id="send">直接匯入</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

{% block js %}
<script>
if("{{ action }}" == "DONE") {
    alert("匯入完成");
}
</script>
{% endblock js %}

{% block ready %}
$("form").submit(function(e) {
    $("body").loading();
});
{% endblock ready %}

src/PMS/inventory/templates/inventory/item_edit.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="row pt-5">
    <div class="col-1"></div>
    <div class="col-10">
        <form id="edit_form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {% crispy form %}
                <fieldset>
                    <legend>Attachment</legend>
                    <div class="row">
                        <div id="div_id_files" class="form-group col-2">
                            <label for="id_files" class="form-control-label">物品圖片</label>
                            <input name="pic1" accept="image/*" class="clearablefileinput" id="id_pic1" type="file">
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="pb-4" style="text-align: center;">
                <input class="btn btn-success" type="submit" value="儲存" />
            </div>
        </form>
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <b>{{ field }}</b>: {{ error }}
            {% endfor %}
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <div class="col-1"></div>
</div>
{% endblock %}
{% block js %}
<script>
changeFamilySelect = function(family_id)
{
    $.get('/inventory/categoryapi/'+family_id, function (data){
        $.each(data, function(index, item){
            item_category.append('<option value="' + item.id + '">' + item.category_name + '</option>')
        })
    })
}

changeCategorySelect = function(category_id)
{
    $.get('/inventory/typeapi/'+category_id, function (data){
        $.each(data, function(index, item){
            item_type.append('<option value="' + item.id + '">' + item.type_name + '</option>')
        })
    })
}

$(function (){
    item_family = $('#id_item_family');
    item_category = $('#id_item_category');
    item_type = $('#id_item_type');

    changeFamilySelect(0, item_family);
    changeCategorySelect(0, item_category);

    item_family.change(function(){
        item_category.empty().append('<option value="">---------</option>');
        item_type.empty().append('<option value="">---------</option>');
        changeFamilySelect(this.value, item_family);
    })

    item_category.change(function(){
        item_type.empty().append('<option value="">---------</option>');
        changeCategorySelect(this.value, item_family, item_category)
    })

    if("{{ mode }}" == "UPDATE") {
        item_family.attr("disabled", true);
        item_category.attr("disabled", true);
        item_type.attr("disabled", true);
    }

    $("#edit_form").submit(function() {
        //唯讀狀態後端無法取值，送出時去掉唯讀
        item_family.attr("disabled", false);
        item_category.attr("disabled", false);
        item_type.attr("disabled", false);
    })
})
</script>
{% endblock js %}

src/PMS/inventory/templates/inventory/item_list.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="p-3">
    <form method="post" action="{% url 'item_list' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy search_form %}
    </form>
    <table id="search_tb" class="table table-striped table-bordered table-hover" data-toggle="table">
        <thead>
            <tr class="text-center table-active">
                <th class="text-center text-nowrap">SN.</th>
                <th class="text-center text-nowrap">ITEM CODE</th>
                <th class="text-center text-nowrap">ITEM TYPE</th>
                <th class="text-center text-nowrap">SPEC</th>
                <th class="text-center text-nowrap">UNIT</th>
                <th class="text-center text-nowrap">IS STOCK</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in page_results %}
            <tr class="data-row">
                <td class="text-center text-nowrap">{{ forloop.counter }}</td>
                <td class="text-center text-nowrap">{{ item.item_code }}</td>
                <td class="text-center text-nowrap">{{ item.item_type.type_name }}</td>
                <td>{{ item.spec }}</td>
                <td class="text-center text-nowrap">{{ item.unit }}</td>
                <td class="text-center text-nowrap">{{ item.is_stock }}</td>
                <td class="text-center text-nowrap">
                    <a href="{% url 'item_detail' item.pk %}" class="btn btn-info">明細</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% include "bases/paginating.html" %}
{% endblock %}
{% block js %}
<script>
    $(function (){
        category = $('#id_category');
        item_type = $('#id_type');

        changeSelect(0, item_type);

        category.change(function(){
            item_type.empty().append('<option value="">---------</option>');
            changeSelect(this.value, item_type)
        })

    })

    changeSelect = function(category_id, asset_type)
    {
        $.get('/inventory/typeapi/'+category_id, function (data){
            $.each(data, function(index, item){
                asset_type.append('<option value="' + item.id + '">' + item.type_name + '</option>')
            })
        })
    }
</script>
{% endblock js %}

src/PMS/inventory/templates/inventory/setting.html
{% extends 'inventory/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<fieldset>
    <div class="row">
        <div class="col p-3" style="font-size: 1.5em">額外退件通知人</div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            設定的內容為「收件人的Mail Address;」
            <form action="" method="post" class="form-group font-weight-bold align-middle" id="setting_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col">
                        <input type="text" name="reject_mail" class="textinput textInput form-control" id="id_reject_mail" value="{{ reject_mail }}">
                    </div>
                    <div class="col">
                        <input class="btn btn-success" type="submit" value="儲存" />
                    </div>
                </div>
            </form>
        </li>
    </ul>
</fieldset>
{% endblock %}
{% block js %}
<script>
    {% if result == "DONE" %}
    alert("設定完成");
    {% endif %}
</script>
{% endblock js %}